spring.application.name=University Managment

# Change the port
server.port=8081

# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/university?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Faizan@123

# Hibernate Strategy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Secret cryptographic signing key
university.app.jwtSecret=SecretUniversitySecurityKeyForRBACSystem2026MustBeLongEnough
# Token lifespan configuration
university.app.jwtExpirationMs=86400000